version: '3.0'
services:
  new_computer:
    container_name: new_computer
    build: .
    volumes:
      - "./.config:/home/user/.config"
      - "./Makefile:/home/user/Makefile"
      - "./test-project:/home/user/dev/test_project"
      - "./setup.sh:/home/user/setup.sh"
    tty: true
    stdin_open: true
    entrypoint: /bin/sh
